(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
    angle
    (p (sine (/ angle 3.0)))))

(display (sine 12.15))
(newline)

#|
	a. How many time is the proceedure p applied when (sine 12.15) is evaluated?

	(sine 12.15)
	(p (sine 4.05))
	(p (p (sine 1.35)))
	(p (p (p (sine 0.449))))
	(p (p (p (p (sine 0.15)))))
	(p (p (p (p (p (sine 0.049))))))

	5 times.

	b. What is the order of growth in space and number of steps (as a function of a) used by
	the process generated by the sine procedure when (sine a) is evaluated?

	programs required space increases slowly with size, not linearly. So,
	
	theta(logn(s)).
|#
